// Generate web/icons.js: inline the Figma-exported SVG icons with fills normalized to
// currentColor so they inherit the parent's CSS color (enables gray→white on expand).
const fs = require("fs");
const path = require("path");

const DIR = path.resolve(__dirname, "../../web/assets/figma");
const OUT = path.resolve(__dirname, "../../web/icons.js");

const KEYS = [
  "icon-jobs", "icon-opportunities", "icon-enabledby", "icon-enablers",
  "icon-valuecreation", "icon-chevron", "icon-search",
  "nav-overview", "nav-valuetree", "nav-timeline",
];

const icons = {};
for (const key of KEYS) {
  let svg = fs.readFileSync(path.join(DIR, key + ".svg"), "utf8");
  svg = svg
    .replace(/var\(--fill-0,\s*[^)]*\)/g, "currentColor")  // recolorable via CSS color
    .replace(/preserveAspectRatio="none"/g, 'preserveAspectRatio="xMidYMid meet"')
    .replace(/\s*\n\s*/g, " ")
    .trim();
  icons[key] = svg;
}

const body =
  "// AUTO-GENERATED by server/scripts/build_icons.cjs — do not edit by hand.\n" +
  "window.FIGMA_ICONS = " + JSON.stringify(icons, null, 0) + ";\n";
fs.writeFileSync(OUT, body);
console.log("Wrote " + OUT + " with " + KEYS.length + " icons (" + body.length + " bytes)");
